### ISSUE TITLE
problems during training

### ISSUE THREAD

**Issue by ydyhello** [qugank/sketch-lattice.github.io#3]
Hello, after reading your paper, I am very interested in it, and try to reproduce the open source code on GitHub. However, during the reproduction process, I encountered some problems: when I trian the model，it always get loss of nan，and this happens during almost same epoch.

So, I modified the code in generation_sketch_gcn.py. The modified adjust_temp function is as follows:

        def adjust_temp(pi_pdf):
            pi_pdf = np.log(1e-3 + pi_pdf) / hp.temperature
            pi_pdf -= pi_pdf.max()
            pi_pdf = np.exp(pi_pdf)
            pi_pdf /= pi_pdf.sum()
            
            # Handle NaN values
            pi_pdf = np.nan_to_num(pi_pdf, nan=1e-7)
            
            return pi_pdf

However, in the end, the loss was negative.

```
]gcn ./models_32_150,epoch: 57500 loss -0.05957534909248352 LR -0.05957534909248352
lr:  0.0009997600275979774
lr:  0.0009997600275979774
 60%|████████████████████████████████████████████████████████████████████████████████▉                                                      | 60000/100001 [2:32:58<1:42:20,  6.51it/s]gcn ./models_32_150,epoch: 60000 loss 0.038562025874853134 LR 0.038562025874853134
lr:  0.0009997500299977016
lr:  0.0009997500299977016
 62%|████████████████████████████████████████████████████████████████████████████████████▎                                                  | 62500/100001 [2:39:37<1:48:11,  5.78it/s]gcn ./models_32_150,epoch: 62500 loss -0.026325106620788574 LR -0.026325106620788574
lr:  0.0009997400324974017
lr:  0.0009997400324974017
 65%|███████████████████████████████████████████████████████████████████████████████████████▋                                               | 65000/100001 [2:45:37<1:25:19,  6.84it/s]gcn ./models_32_150,epoch: 65000 loss 0.033327776938676834 LR 0.033327776938676834
lr:  0.0009997300350970768
lr:  0.0009997300350970768
143
 67%|███████████████████████████████████████████████████████████████████████████████████████████                                            | 67500/100001 [2:51:53<1:17:21,  7.00it/s]gcn ./models_32_150,epoch: 67500 loss -0.08081778138875961 LR -0.08081778138875961
lr:  0.000999720037796726
lr:  0.000999720037796726
 70%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                        | 69999/100001 [2:57:49<1:14:03,  6.75it/s]gcn ./models_32_150,epoch: 70000 loss 0.043715376406908035 LR 0.043715376406908035
lr:  0.0009997100405963481
lr:  0.0009997100405963481
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                     | 72500/100001 [3:03:54<1:19:16,  5.78it/s]gcn ./models_32_150,epoch: 72500 loss -0.07980106770992279 LR -0.07980106770992279
lr:  0.0009997000434959422
lr:  0.0009997000434959422
 75%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                                 | 75000/100001 [3:10:04<1:02:04,  6.71it/s]gcn ./models_32_150,epoch: 75000 loss 0.03005499765276909 LR 0.03005499765276909
lr:  0.0009996900464955072
lr:  0.0009996900464955072
26
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                              | 77500/100001 [3:16:08<47:15,  7.94it/s]gcn ./models_32_150,epoch: 77500 loss -0.09152494370937347 LR -0.09152494370937347
lr:  0.0009996800495950422
lr:  0.0009996800495950422

```

Continuing to train, an error occurred:

```
Traceback (most recent call last):
  File "generation_sketch_gcn.py", line 507, in <module>
    model.train(epoch)
  File "generation_sketch_gcn.py", line 317, in train
    self.conditional_generation(epoch)
  File "generation_sketch_gcn.py", line 385, in conditional_generation
    s, dx, dy, pen_down, eos = self.sample_next_state()
  File "generation_sketch_gcn.py", line 419, in sample_next_state
    pi_idx = np.random.choice(hp.M, p=pi)
  File "mtrand.pyx", line 932, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities do not sum to 1
```

I would like to ask if there is a problem with the code above on GitHub, or there are other versions. Thank you so much for taking the time to answer my questions!

**Comment by qugank** [comment]
Hi, I think nan happens at the very late stage of the training, and the model should have been well-trained when you observe it. So you do not need to handle it manually, just try to use the best checkpoint so far.

**Comment by ydyhello** [comment]
> Hi, I think nan happens at the very late stage of the training, and the model should have been well-trained when you observe it. So you do not need to handle it manually, just try to use the best checkpoint so far.

Thank you very much for your answer, that is, when NAN appears, does it mean that the training is over?

**Comment by qugank** [comment]
Yes, you can say that.

**Comment by ydyhello** [comment]
> Yes, you can say that.

Thank you very much for your answer!
